---
# tasks file for glusterFS

- name: Add port to firewalld
  firewalld:
    port: "{{ item.port }}/{{ item.porto }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items:
    - { port: "24007-24009", porto: "tcp" }
    - { port: "111", porto: "tcp" }
    - { port: "139", porto: "tcp" }
    - { port: "445", porto: "tcp" }
    - { port: "965", porto: "tcp" }
    - { port: "2049", porto: "tcp" }
    - { port: "631", porto: "tcp" }
    - { port: "38465-38469", porto: "tcp" }
    - { port: "49152-49251", porto: "tcp" }
    - { port: "111", porto: "udp" }
    - { port: "963", porto: "udp" }
  when: "'gluster-server' in group_names"


- name: Add service to firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items:
    - nfs
    - samba
    - samba-client
  when: "'gluster-server' in group_names"




- name: install package centos-release-gluster
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - centos-release-gluster

- name: install package glusterfs-server
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - glusterfs-server
  when: "'gluster-server' in group_names"


- name: install package glusterfs-client
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - glusterfs-client
  when: "'gluster-client' in group_names"

- name: restart glusterd
  service:
    name: glusterd
    state: started
    enabled: yes
  when: "'gluster-server' in group_names"
