---
# vars file for heketi

role_directory: ./roles/heketi/files/

DOWNLOAD_URL_HEKETI: https://github.com/heketi/heketi/releases/download/v10.1.0
HEKETI_VER: heketi-v10.1.0.linux.amd64.tar.gz
url_heketi: "{{ DOWNLOAD_URL_HEKETI }}/{{ HEKETI_VER }}"


DOWNLOAD_URL_HEKETI_ENV: https://raw.githubusercontent.com/heketi/heketi/master/extras/systemd/heketi.env